apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido
  labels:
    app: pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedido
  template:
    metadata:
      labels:
        app: pedido
    spec:
      containers:
        - name: pedido
          image: diegobbrito17/pedidos:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: db_database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: db_password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: db_port
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: db_server
            - name: DB_PASSWORD_ROOT
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: db_root_password
            - name: BACK_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: back_port
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: rabbitmq_port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: rabbitmq_password
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: secret
            - name: PRODUTO
              valueFrom:
                secretKeyRef:
                  name: secret-pedido
                  key: produto