apiVersion: v1
kind: Service
metadata:
  name: pedidodb
  labels:
    app: pedidodb
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: pedidodb
    tier: database
  clusterIP: None
